plugins {
    id 'java-library'
    alias(libs.plugins.freefair.lombok)
    id 'maven-publish'
    id "jacoco"
}

group = 'io.oxalate.fillstation'
version = libs.versions.release.version.get()

jar {
    archiveFileName = "${rootProject.name}-api-${version}.jar"
}

java {
    // Attach sources and javadoc for Maven consumers
    withSourcesJar()
    withJavadocJar()
}

// Quiet javadoc warnings as we're using Lombok which does not generate documentation for the generated methods
tasks
        .withType(Javadoc)
        .configureEach {
            options
                    .addStringOption('Xdoclint:all,-missing', '-quiet') // keep other checks, ignore missing docs
        }

repositories {
    mavenCentral()
}

dependencies {
    api libs.jackson.databind
    api libs.spring.boot.starter.web
    api libs.spring.data.jpa
    implementation libs.swagger.annotations
    implementation libs.spring.boot.starter.security
    implementation libs.jakarta.validation.api
    testImplementation libs.mockito.junit.jupiter
    testImplementation libs.junit.jupiter
    testImplementation libs.junit.platform.launcher
}

jacoco {
    toolVersion = libs.versions.jacoco.get()
}

tasks
        .named('test') {
            useJUnitPlatform()
        }

test {
    finalizedBy jacocoTestReport
}

jacocoTestReport {
    dependsOn test
    reports {
        xml
                .required = true
    }
}
